Repository aggie-coding-club/Rev-Registration, pull requests merged in 2020-04, with the labels that each got.

#173 Fixed bug when clicking on second course card
  autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/BasicSelect/BasicSelect.tsx
  autoscheduler/frontend/src/tests/CourseSelectColumn.test.tsx
Labels: bug, frontend

#170 Implemented api/grades route
  autoscheduler/scraper/tests/api_tests.py
  autoscheduler/scraper/urls.py
  autoscheduler/scraper/views.py
Labels: backend

#178 Merge backend/master into master
  .github/lint-requirements.txt
  .gitignore
  autoscheduler/autoscheduler/settings/base.py
  autoscheduler/autoscheduler/urls.py
  autoscheduler/scraper/management/commands/scrape_courses.py
  autoscheduler/scraper/management/commands/scrape_grades.py
  autoscheduler/scraper/management/commands/utils/__init__.py
  autoscheduler/scraper/management/commands/utils/pdf_helper.py
  autoscheduler/scraper/management/commands/utils/pdf_parser.py
  autoscheduler/scraper/models/__init__.py
  autoscheduler/scraper/models/course.py
  autoscheduler/scraper/models/grades.py
  autoscheduler/scraper/models/section.py
  autoscheduler/scraper/serializers.py
  autoscheduler/scraper/tests/api_tests.py
  autoscheduler/scraper/tests/commands/pdf_parser_tests.py
  autoscheduler/scraper/tests/commands/scrape_courses_tests.py
  autoscheduler/scraper/tests/commands/scrape_grades_tests.py
  autoscheduler/scraper/tests/data/grd20153MD.pdf
  autoscheduler/scraper/tests/data/grd20191AP.pdf
  autoscheduler/scraper/tests/data/section_input.json
  autoscheduler/scraper/tests/models_tests.py
  autoscheduler/scraper/tests/utils/load_json.py
  autoscheduler/scraper/urls.py
  autoscheduler/scraper/views.py
  requirements.txt
Labels: backend

#180 Updated README
  README.md
Labels: documentation

#200 Meeting days should start with Monday
  autoscheduler/frontend/src/components/App/testMeetings.ts
  autoscheduler/frontend/src/components/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.tsx
  autoscheduler/frontend/src/components/Schedule/Schedule.tsx
  autoscheduler/frontend/src/redux/testData.ts
Labels: change, frontend

#196 New components for scheduling page
  autoscheduler/frontend/src/components/App/Test.tsx
  autoscheduler/frontend/src/components/GenericCard/GenericCard.css
  autoscheduler/frontend/src/components/GenericCard/GenericCard.css.d.ts
  autoscheduler/frontend/src/components/GenericCard/GenericCard.tsx
  autoscheduler/frontend/src/components/SchedulingPage/ConfigureCard/ConfigureCard.css
  autoscheduler/frontend/src/components/SchedulingPage/ConfigureCard/ConfigureCard.css.d.ts
  autoscheduler/frontend/src/components/SchedulingPage/ConfigureCard/ConfigureCard.tsx
  autoscheduler/frontend/src/components/SchedulingPage/ConfigureCard/generateSchedulesMock.ts
  autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.css
  autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.css.d.ts
  autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/SchedulePreview.tsx
  autoscheduler/frontend/src/tests/ConfigureCard.test.tsx
  autoscheduler/frontend/src/tests/SchedulePreview.test.tsx
  autoscheduler/frontend/src/types/Grades.ts
Labels: feature, frontend

#213 Made deploy workflow only run on pushes to master
  .github/workflows/deploy-workflow.yml
Labels: bug, deployment

#214 Corrected deploy-workflow syntax
  .github/workflows/deploy-workflow.yml
Labels: bug, deployment

#216 Changed scrape_grades to bulk query Sections
  autoscheduler/scraper/management/commands/scrape_grades.py
Labels: backend, change

#226 Sort api/course/search results by dept and course_num
  autoscheduler/scraper/views.py
Labels: backend, change

#231 Removed unnecessary f-string from scrape_grades
  autoscheduler/scraper/management/commands/scrape_grades.py
Labels: backend

#224 Changed scrape_grades to use multiprocessing
  autoscheduler/scraper/management/commands/scrape_grades.py
Labels: backend, change
