Repository aggie-coding-club/Rev-Registration, pull requests merged in 2020-02, with the labels that each got.

#129 Fixes for course scraping
  autoscheduler/scraper/management/commands/scrape_courses.py
Labels: backend

#133 Added CI build badges to README
  README.md
Labels: enhancement

#137 Added mac install instructions for main readme
  README.md
Labels: enhancement

#152 Section API Fixes
  autoscheduler/scraper/serializers.py
  autoscheduler/scraper/tests/api_tests.py
Labels: backend, continuous-integration
